---
datashield_username: mdr-ra
datashield_uid: 1090

domain_name: mdr-ra

podman_network: datashield

public_https_port: 8000

allowed_ssh_client_networks:
  - 127.0.0.1/32
allowed_https_client_networks:
  - 127.0.0.1/32
